### ISSUE TITLE
Gallery background animation doesn't work on Firefox

### ISSUE THREAD

**Issue by WylfredWen** [Yuying-Jin/CS421proj#1]
The background animation for Gallery  doesn't work on Brave browser. About Us works just fine. Need investigation.

Typo: It occurs on Brave browser (Chromium based browser), not Firefox

**Comment by Yuying-Jin** [comment]
It is wired. Both About Us and Gallery work well on my laptop.

**Comment by WylfredWen** [comment]
Fixed by removing then re-adding the "back to top" button
`<a href="#top">
    <svg id="goTop">
        <g transform="translate(30,15)" stroke-width="4" stroke="white" stroke-linecap="round">
            <line x1="0" y1="30" x2="0" y2="0"/>
            <line x1="0" x1="0" x2="-15" y2="15"/>
            <line x1="0" x1="0" x2="15" y2="15"/>
        </g>
    </svg>
</a>`

IDK why thats the case...
